/* confdefs.h */
#define PACKAGE_NAME "imedia"
#define PACKAGE_TARNAME "imedia"
#define PACKAGE_VERSION "0.1.00"
#define PACKAGE_STRING "imedia 0.1.00"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define PACKAGE "imedia"
#define VERSION "0.1.00"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
